services:
  db:
    container_name: postgres
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      restart: always
  
  pgadmin:
    depends_on:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4:8.6
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: code@dev.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    restart: always